#!/usr/bin/env node

/**
 * Module dependencies.
 */

var fs = require('fs');
var path = require('path');
var util = require('util');
var _ = require('lodash');

var config = JSON.parse(fs.readFileSync(path.join(__dirname, 'jsvex.json')));
var libs = Object.keys(config);
var files = [];
var cmdPattern = "node node_modules/tern/bin/condense --name %s --plugin doc_comment --def browser --no-spans %s > %s\n";
var shell = "";

libs.map(function(name) {
    var priority = config[name].priority;
    delete config[name].priority;
    var versions = Object.keys(config[name]);
    versions.map(function(version) {
        if (config[name][version].ignore) {
            return;
        }
        var data = {
            label: name,
            version: version,
            values: config[name][version].cdn,
            priority: priority,
            file: config[name][version].local.length ? 'def~' + name + '~' + version : undefined
        };
        files.push(data);
        var fp = 'output/' + data.file + '.json';
        try {
            var stats = fs.statSync(fp);
            console.log('File exists: ' + fp);
        }
        catch(err) {
            // file does not exist
            if (config[name][version].local.length)
                shell += util.format(cmdPattern, data.label,
                    config[name][version].local[0], fp);
        }
    });
});

var index = [];
var grouped = _.groupBy(files, 'label');
libs.sort(function (a, b) {
    return a.toLowerCase().localeCompare(b.toLowerCase());
});
libs.map(function(name) {
    index.push({
        label: name,
        priority: grouped[name][0].priority,
        versions: _.map(grouped[name], 'version').sort().reverse(),
        data: _.transform(_.groupBy(grouped[name], 'version'), function(result, value, key) {
            result[key] = {values: value[0].values, file: value[0].file}
        }, {})
    });
});

/*
 The following error when compiling some libraries is caused by read-only fields:
 .../node_modules/tern/lib/condense.js:219
 if (!hop(base, last)) base[last] = type.nameOverride || type.path;
 ^
 Fix this by removing 'use-strict' tern/lib/tern.js, tern/lib/condense.js, tern/lib/infer.js
 */
fs.writeFile(path.join(__dirname, "/output/index.json"), JSON.stringify(index, "", " "));
fs.writeFile(path.join(__dirname, "/make.sh"), shell);
